language: php

notifications:
    on_success: change
    on_failure: change

php:
    - 7.0
    - 5.6
    - 5.3
    - 5.2
    - hhvm

env:
    # latest stable:
    - WP_VERSION=4.2 WP_MULTISITE=0
    - WP_VERSION=4.2 WP_MULTISITE=1
    # previous stable:
    - WP_VERSION=4.1 WP_MULTISITE=0
    - WP_VERSION=4.1 WP_MULTISITE=1
    # earliest supported:
    - WP_VERSION=3.1 WP_MULTISITE=0
    - WP_VERSION=3.1 WP_MULTISITE=1

matrix:
    exclude:
        # don't test 3.1 on hiphop:
        - php: hhvm
          env: WP_VERSION=3.1 WP_MULTISITE=0
        - php: hhvm
          env: WP_VERSION=3.1 WP_MULTISITE=1
        # don't test 3.1 on PHP 7:
        - php: 7.0
          env: WP_VERSION=3.1 WP_MULTISITE=0
        - php: 7.0
          env: WP_VERSION=3.1 WP_MULTISITE=1
    allow_failures:
        # allow failures on PHP 7 for now:
        - php: 7.0

install:
    - bash bin/install.sh

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
    - phpunit
    - bash bin/script.sh
